KPV-1617
Kuorum/kuorum pull request #2
Opened 2021-02-17 11:35 UTC by JavierKuorum

It was requested that the type of validation of the platform has to be by default without validation, it has been changed so that it is fulfilled by testing it in the test correctly

2021-02-18 13:47 UTC, alberKuorum requested changes

2021-02-18 13:47 UTC, alberKuorum commented on grails-app/controllers/kuorum/politician/CampaignController.groovy
> +            //command.validationType = CustomDomainResolver.domainRSDTO?.validation? CampaignValidationTypeRDTO.DOMAIN: CampaignValidationTypeRDTO.NONE
Use code reformat in intellij please

2021-02-18 20:36 UTC, iduetxe commented on grails-app/controllers/kuorum/politician/CampaignController.groovy
> +            //command.validationType = CustomDomainResolver.domainRSDTO?.validation? CampaignValidationTypeRDTO.DOMAIN: CampaignValidationTypeRDTO.NONE
Yes, the new logic is correct.

2021-02-19 08:38 UTC, JavierKuorum commented
Finish task

2021-02-19 09:51 UTC, alberKuorum approved these changes

2021-02-19 09:51 UTC, merged