Requested to increase the line spacing of questions.
Kuorum/kuorum pull request #278
Opened 2022-06-29 18:53 UTC by PedroR-dev

2022-06-29 19:49 UTC, PedroR-dev commented
In the second commit, the percentage has been modified so that the button does not clash with the text.

2022-06-30 07:24 UTC, iduetxe requested changes

2022-06-30 07:24 UTC, iduetxe commented on web-app/css/custom.css
> +    line-height: 175%;
I prefer an absolute height. 

Other point, is that the first line is not centered with the bullet icon

2022-07-14 14:26 UTC, iduetxe approved these changes

2022-07-14 14:27 UTC, merged