KPV-2536 :: A bunch of small issues requested by cinfa
Kuorum/kuorum pull request #372
Opened 2022-09-16 10:27 UTC by iduetxe

2022-09-19 13:22 UTC, DavidSanFer555 commented
Close icon too close to text
![Screenshot from 2022-09-19 15-16-00](https://user-images.githubusercontent.com/111739783/191027105-bd86feb3-58e8-4fa2-a865-1e2b9e40509a.png)

2022-09-19 13:24 UTC, DavidSanFer555 commented on grails-app/i18n/messages.properties
> +contestApplication.modal.confirmVote.title=Voto en {0}
Spanish messages on english file?????

2022-09-19 13:41 UTC, DavidSanFer555 commented
"Comrpueba los resutlados en el ranking o en el listado de abajo" sigue sin corregir

2022-09-19 14:04 UTC, DavidSanFer555 commented
Contest screen, with little tile for applications, don't allow any vote action neither put any error on logs.

2022-09-19 14:07 UTC, DavidSanFer555 commented
Info pre vote is displayed on application screen when try to vote even you voted before

2022-09-19 14:08 UTC, DavidSanFer555 requested changes
Several comments on pullrequest without line reference

2022-09-20 15:07 UTC, iduetxe commented on grails-app/i18n/messages.properties
> +contestApplication.modal.confirmVote.title=Voto en {0}
Fiuu. Fixed

2022-09-22 16:12 UTC, DavidSanFer555 approved these changes

2022-09-22 16:12 UTC, merged