KPV-2334:: Application contest new report
Kuorum/kuorum pull request #377
Opened 2022-09-22 10:21 UTC by DavidSanFer555

New report of application contest. Cinfa definition

2022-09-22 15:13 UTC, pverdu-kuorum requested changes
Just rename some variables into your new abstract function which make the AJAX request.

2022-09-22 15:13 UTC, pverdu-kuorum commented on grails-app/controllers/kuorum/politician/CampaignController.groovy
> +        Long participatoryBudgetId = Long.parseLong(params.campaignId)
The name of the variables are specific for the Campaign abstraction.

2022-09-23 07:40 UTC, pverdu-kuorum requested changes
Extract sendReport to Campaign service.

2022-09-23 07:40 UTC, pverdu-kuorum commented on grails-app/controllers/kuorum/politician/CampaignController.groovy
> +        participatoryBudgetService.sendReport(campaignUser, campaignId, reportApiMethod)
Move to CampaignService to uncouple of ParticipatoryBudgetService

2022-09-23 12:14 UTC, iduetxe approved these changes

2022-09-23 12:19 UTC, pverdu-kuorum approved these changes

2022-09-23 12:19 UTC, merged