KPV-2579 Changed voting icon in all places it's used from fa-scroll to fa-box-ballot.
Kuorum/kuorum pull request #399
Opened 2022-10-10 09:26 UTC by PedroR-dev

2022-10-13 12:29 UTC, iduetxe requested changes

2022-10-13 12:29 UTC, iduetxe commented on grails-app/views/contest/showModules/_cContestStats.gsp
> +        <span class="fal fa-box-ballot" aria-hidden="true"></span>
This should be fa-scroll because this stats talk about the number of applications, not votes

2022-10-18 14:16 UTC, pverdu-kuorum approved these changes

2022-10-19 19:47 UTC, iduetxe approved these changes
Lo reviso directamente todo junto

2022-10-19 19:48 UTC, merged