Hide/Show register button FRONT
Kuorum/kuorum pull request #645
Opened 2023-07-17 16:48 UTC by PedroR-dev

Create logic to hide or show register button based on api flag. Update RegisterController to prevent sign up if button is hidden.
Limited permissions so that the admin can only modify this field, but not all domain config. Created new POE entries

2023-07-18 13:55 UTC, iduetxe requested changes

2023-07-18 13:55 UTC, iduetxe commented on grails-app/controllers/springSecurity/RegisterController.groovy
> +        registerButtonDisabledRedirect();
Rename to checkRegisterActiveAndRedirect

2023-07-18 13:55 UTC, iduetxe commented on src/groovy/kuorum/web/admin/domain/DomainValidationCommand.groovy
> +        firstFactorValidation nullable: true
REvert

2023-07-18 13:55 UTC, iduetxe commented on src/groovy/kuorum/web/admin/domain/DomainValidationCommand.groovy
> +    Boolean showRegisterButton
Revert. As we talked this field will be in other command

2023-07-18 17:34 UTC, PedroR-dev commented
A futuro cuando se pueda me encantaría juntar la lógica de los dos checkbox, creo que no tiene sentido que estén separados

2023-07-19 08:31 UTC, iduetxe approved these changes

2023-07-19 08:31 UTC, merged